prefer-html: true
project:
  type: book
  output-dir: docs
book:
  title: ZVX108E Hydrology
  subtitle: Hydrology WS 24/25 Sessions Companion
  author: Petr Pavlík
  favicon: cover.png
  repo-url: https://github.com/petr-pavlik/Hydrology_ZVX108E/
  repo-actions:
  - edit
  - issue
  date: today
  chapters:
  - index.qmd
  - intro.qmd
  - 01_R.qmd
  - 02_statistics.qmd
  - 03_gis.qmd
  # - 04_interpolation.qmd
  downloads:
  - pdf
  - epub
  sidebar:
    title: Hydrology ZVX108E
    pinned: true
  search:
    location: sidebar
    type: textbox
bibliography: references.bib
format:
  html:
    page-layout: article
    theme:
    - cosmo
    - style.scss
    max-width: 1600px
    code-fold: show
    highlight-style: syntax.theme
    code-annotations: hover
    fig-format: svg
    fig-dpi: 400
    fig-cap-location: bottom
    css: include/webex.css
    include-after-body: include/webex.js
  pdf:
    documentclass: scrreprt
editor: visual
lang: en-EN
quarto:
  footnotes:
    footnoteRef: <i class="fa-duotone fa-arrow-left"></i>
