# Introduction {.unnumbered}

The **ZVX108E Hydrology** taught at the Czech University of Life Sciences is an introductory undergraduate course with students of various scientific background, many of whom do not possess knowledge of any programming language yet. Therefore we introduce within the sessions the **R programming language**, which serves for decades as a great tool for scientific data processing, statistical evaluation, visualization and reporting. The choice of R over other tools (like Matlab, Python or Julia) is opinionated. R is told to be *"developed by statisticians for statisticians"* and such as fits well into the workflow of hydrological data processing, which in most of scenarios start with some statistical analysis. We believe that the language is more straightforward to learn than others, especially non-programmers and does not maim a student's workflow with plethora of environments and mutually incomparable versions. Though there is a saying *"Python is the second best language for everything"* a statement with which we as authors fully agree. In recent years Python also made a huge step forward in making things more straightforward and many formerly R's bound features like RStudio/RMarkdown made a breach to Python's community.

\
Since the course only contains six practical sessions, oriented to various parts of hydrology, we focus on the basic and merit. The *book* starts with a fairly fast-paced introduction to R language and it is due to this, that it did not end far from it. We purposefully avoid using what is considered a modern approach in data workflow (mainly with the help from **tidyverse** & **data.table**) as well using *native pipe* `|>` operator, a syntactical feature from `(R>=4.1.0)` which we consider too big of a change of the programming paradigm for a newbie.

This text was created with the use of `r stringr::str_flatten(c(version$major, ".", version$minor))` and namespaces of following packages:

```{r, echo=FALSE}
installed.packages()[installed.packages()[, 1] %in% loadedNamespaces(), ][, c("Version")] |> 
  data.frame() |> 
  setNames("Version") 
```

Reproduction of all the materials should be possible using the same versions.
