::: download_btn
```{css}
#| echo: false

.btn-default,
.btn-default:hover,
.btn-default:active {
  font-size: 16px;
  color: dimgrey;
  background-color: transparent;
  border-color: transparent;
}

.btn-default:hover {
  color: #0e0e0e;
  transition: 0.2s;
}

```

A list of datasets, used within the sessions.

```{r}
#| echo: false

library(downloadthis)

mtcars %>%
  download_this(
    output_name = "mtcars data set",
    output_extension = ".csv",
    button_label = "mtcars.csv",
    button_type = "default",
    has_icon = TRUE,
    icon = "fa fa-file-csv"
  )
```

```{r}
#| echo: false

iris %>%
  download_this(
    output_name = "Iris data set",
    output_extension = ".csv",
    button_label = "iris.csv",
    button_type = "default",
    has_icon = TRUE,
    icon = "fa fa-file-csv"
  )
```

```{r}
#| echo: false

palmerpenguins::penguins %>%
  download_this(
    output_name = "penguins data set",
    output_extension = ".csv",
    button_label = "penguins.csv",
    button_type = "default",
    has_icon = TRUE,
    icon = "fa fa-file-csv"
  )
```
:::

# Data and companion structure

The data for all the chapters
At the beginning of each chapter there is a list of needed knowledge and  that you need to grasp in order
## Data download

## Recommended literature

See @knuth84 for additional discussion of literate programming.
